services:
  nodejs:
    image: node:12
    container_name: web-nodejs
    working_dir: /application
    volumes:
      - ./application:/application
    command: >
      sh -c "npm install && npm run build"

  nginx:
    image: nginx:latest
    container_name: web-nginx
    ports:
      - 80:80
    volumes:
      - ./application/build:/var/www
      - ./container/nginx/core:/etc/nginx/conf.d
      - ./container/nginx/logs:/var/log/nginx/
      - ./container/nginx/html:/usr/share/nginx/html/

  proxy:
    image: node:12
    container_name: web-proxy
    working_dir: /proxy
    ports:
    - 3001:3001
    volumes:
    - ./proxy:/proxy
    command: >
      sh -c "npm install && nohup node index.js > /dev/null 2>&1 &"
